### PR TITLE
Begin work on differentiating URS pages from URS_taxid pages

### LINKED ISSUE #357: Make the difference between a generic page and a species specific page clear
From the SAB it seems that it is basically impossible to tell if you are looking at an species specific page or a generic page. This needs to be fixed. We may also want to consider different functionality for these pages. For example on a generic page the taxonomic tree may be more interesting than on a species specific page. Either way we must do something to distinguish these two. 

- [ ] hide publications and annotations
- [ ] provide a list of URS_taxid entries
- [ ] bring taxonomy component to the main tab

### PR DESCRIPTION
**Pull request by AntonPetrov**
The idea is to clearly differentiate between URS and URS_taxid pages.

**Examples**
- miRNA with 1 species: http://localhost:8000/rna/URS000075A3E5/
- miRNA with 4 species: http://localhost:8000/rna/URS0000759B6D/
- tRNA with 38 species:  http://localhost:8000/rna/URS00001DA281

⚙️🛠 Not ready for merging - I would like to clean up the `sequence.html` template.

Fixes #357

### CODE REVIEW

**Comment by AntonPetrov** [comment]
@blakesweeney @BurkovBA Please have a look at the new non-species-specific pages in this branch and let me know if you have any feedback. Thank you!

**Comment by BurkovBA** [comment]
I don't mean to be critical, but may I express some suggestions?

First, I'd expect some consistency in the common part of species-specific and non-species-specific pages, in the location of "87 nucleotides" signature etc.

Second, I think the non-species specific page is very patchy. The fonts with links to species-specific pages are too big in my opinion and inconsistent with the rest of the website. Maybe the green well with "URS00001DA281 is a tRNA found in 38 species" is unnecessary - again, it makes the page too unstructured.

**Comment by blakesweeney** [comment]
I agree with boris about the font size and green well. I'd shrink the font to the standard size we use and replace the green well with something more similar to the standard section we use. Also, are the organism names in the list not part of the link to species specific pages?

**Comment by AntonPetrov** [comment]
Thanks folks! Will see what I can do. 

My main concern is that Google keeps a bunch of URS (no taxid) pages in the index, so it should be clear what to do next for people who navigate there from Google. That's what I tried to do with the green banner and the large font for the URS-specific links.

**Comment by AntonPetrov** [comment]
Closed in favour of #493

**Pull request closed without merging**
