### PR TITLE
Display Ensembl Compara

### LINKED ISSUE #32: Show orthologs (where possible)
Start with human and mouse.

### LINKED ISSUE #342: Provide links to comparative view in Ensembl
This is a suggestion from SAB. It would be really useful to see comparisons between different organisms. This isn't something that RNAcentral does but we can at least to link to Ensembl comparative view.

### LINKED ISSUE #445: Display ensembl compara
I have done and initial import of Ensembl compara data into the `ensembl_compara` table. We now need to display the data somehow. For the moment just linking to the trees that ensembl provides is a good start. The links should go to pages like:

http://www.ensembl.org/Nomascus_leucogenys/Gene/Compara_Tree?g=ENSNLEG00000021462;r=1a:22821011-22821081;t=ENSNLET00000026487

it seems like we can use a url like: `http://www.ensembl.org/Nomascus_leucogenys/Gene/Compara_Tree?t=<transcript_id>` to get a valid location.

### PR DESCRIPTION
**Pull request by AntonPetrov**
**Features**
✅ links to Ensembl Compara tree
✅ paginates after 50 sequences
✅ identical sequences marked with a badge

**Examples**
- Many related sequences (supports pagination): http://localhost:8000/rna/URS0000001EB3/9606
- Only one related sequence: http://localhost:8000/rna/URS0000001A7A/9606
- No related sequences (nothing is shown): http://localhost:8000/rna/URS000075D95B/9606

⚠️ Do not merge until the production databases have the Compara tables ⚠️ 

@blakesweeney Please review on a local machine using the _TST_ database when you get a chance. Thanks!

Fixes #445, closes #342, and closes #32.

### CODE REVIEW

**Comment by blakesweeney** [comment]
The pages display the data nicely enough. There is one change I think we should make though. We need to display something when there is no data available. Specifically we need to distinguish between cases of no data available because it isn't computed:

http://localhost:8000/rna/URS000075D95B/9606

or a genome where this is not yet done. Or cases where there are no related sequences.

**Comment by AntonPetrov** [comment]
Good point! Will look into it.

**Comment by AntonPetrov** [comment]
@blakesweeney Now the Compara messages are customised. Test cases:
- not an ensembl sequence: http://localhost:8000/rna/URS000075C808/9606
- incompatible RNA type (like lncRNA) - when it's in Ensembl but `urs_taxid` is not in `ensembl_compara`: http://localhost:8000/rna/URS000025784F/9606
- no related sequences (`homology_id` is unique): http://localhost:8000/rna/URS00008118F7/10090

⚠️ Do not merge until the production databases have the Compara tables ⚠️

**Comment by blakesweeney** [comment]
Just FYI, prod now has `ensembl_compara`.

**Comment by blakesweeney** [comment]
I like how the different cases of no data are explained. It looks good to me. The only issue I see is that the font is a different colour in the Ensembl Compara section. Not sure if that is an issue on my end though. Other than that I think it is ready to merge.

**Pull request merged**
