### PR TITLE
Display mature miRNA features

### PR DESCRIPTION
**Pull request by AntonPetrov**
@blakesweeney could you please test this locally when you get a chance? I would like to keep test.rnacentral.org on the 2Ds branch for external collaborators.

Example page: http://localhost:8000/rna/URS00001AC666/7227

### CODE REVIEW

**Comment by blakesweeney** [comment]
I haven't checked the functionality yet, but looking at the code I have a concern. Why not have a generic sequence feature API endpoint and approach. We are going to be adding more features (I'm working on exon/intron junctions for example). Adding an endpoint for each type of feature seems overly complex. I'd suggest extending the current endpoints and javascript to handle more than one feature type correctly.

**Comment by AntonPetrov** [comment]
Good suggestion, thanks! Here is a generalised version. 

Examples:
only CRS: http://localhost:8000/rna/URS000019E0CD/9606
only miRNA: http://localhost:8000/rna/URS00001AC666/7227
CRS and miRNA: http://localhost:8000/rna/URS000075CB3A/9606
only Rfam (no miRNA or CRS): http://localhost:8000/rna/URS00004D18E1/9606

**Comment by blakesweeney** [comment]
I like the feature! I've looked at the site a bit and everything seems to work and it looks good.

**Comment by AntonPetrov** [comment]
Thanks Blake! Merging and deploying then.

**Pull request merged**
